apiVersion: v1
clusters:
- name: devsoc
  cluster:
    certificate-authority: /home/chino/certs/devsoc/certificate-authority.crt
    server: https://51.161.198.241:6443
- name: homelab
  cluster:
    certificate-authority: /home/chino/certs/homelab/certificate-authority.crt
    server: https://192.168.86.38:6443
- name: wheatley
  cluster:
    certificate-authority: /home/chino/certs/homelab/certificate-authority.crt
    server: https://wheatley.cse.unsw.edu.au:7654
contexts:
- context:
    cluster: devsoc
    user: ethan
  name: devsoc
- context:
    cluster: homelab
    user: chino
  name: homelab
- context:
    cluster: wheatley
    user: ethan-wheetly
  name: wheatley
current-context: homelab
kind: Config
preferences: {}
users:
- name: chino
  user:
    client-certificate: /home/chino/certs/homelab/client-certificate.crt
    client-key: /home/chino/certs/homelab/client-key.key
- name: ethan
  user:
    client-certificate: /home/chino/certs/devsoc/client-certificate.crt
    client-key: /home/chino/certs/devsoc/client-key.key
- name: ethan-wheetly
  user:
    client-certificate: /home/chino/certs/wheatley/client-certificate.crt
    client-key: /home/chino/certs/wheatley/client-key.key

  # crts and keys are base64 encoded and found at /etc/rancher/k3s/k3s.yaml.
  # They must be decoded before uploading to the specific files.
